version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kyc_verify
      POSTGRES_USER: kyc_user
      POSTGRES_PASSWORD: Strong1221!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kyc_user -d kyc_verify"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    
    environment:
      SECRET_KEY: qs6_5W9Qz9BuEX1pG0MRX9wUIl47_O2wRObCUcx4r0c
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: