version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kyc_verify
      POSTGRES_USER: kyc_user
      POSTGRES_PASSWORD: Strong1221!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://kyc_user:Strong1221!@db:5432/kyc_verify
      SECRET_KEY: qs6_5W9Qz9BuEX1pG0MRX9wUIl47_O2wRObCUcx4r0c
    depends_on:
      - db

volumes:
  postgres_data:
