name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: kyc_verify
          POSTGRES_USER: kyc_user
          POSTGRES_PASSWORD: Strong1221!
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U kyc_user" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      DATABASE_URL: postgresql://kyc_user:Strong1221!@localhost:5432/kyc_verify
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Alembic migrations
        run: |
          alembic upgrade head

      - name: Run tests (add your tests here)
        run: |
          echo "🧪 No tests yet. You should add tests soon!"

      - name: Deploy to Render
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK
